/// <reference types="vite/client" />

// Injected at build time from package.json (see electron.vite.config.ts renderer define).
declare const __APP_VERSION__: string

// Generated by `npm run licenses:generate` (runs automatically before dev/build).
// Keyed by "name@version"; fields follow scripts/license-fields.json.
declare module '@/generated/licenses.json' {
  const licenses: Record<
    string,
    { licenses?: string; repository?: string; publisher?: string }
  >
  export default licenses
}
